{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNkBJyj55kcAhWARjqFZLYV",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rkyadav1480-boop/Sharemarket/blob/main/Breakout_in_weekly_chart.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 8,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "lJ4wO94NAzBs",
        "outputId": "428a5c66-bbae-41ca-a95a-5e86395d8227"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Nifty 500 सिंबल लाए जा रहे हैं...\n",
            "सफलतापूर्वक 500 Nifty 500 सिंबल लाए गए।\n",
            "Nifty 500 स्टॉक्स के लिए साप्ताहिक ब्रेकआउट स्कैन चलाया जा रहा है...\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "ERROR:yfinance:$GMRINFRASTRUCT.NS: possibly delisted; no price data found  (period=2y) (Yahoo error = \"No data found, symbol may be delisted\")\n",
            "ERROR:yfinance:$ISEC.NS: possibly delisted; no price data found  (period=2y) (Yahoo error = \"No data found, symbol may be delisted\")\n",
            "ERROR:yfinance:$LTIM.NS: possibly delisted; no price data found  (period=2y) (Yahoo error = \"No data found, symbol may be delisted\")\n",
            "ERROR:yfinance:$PEL.NS: possibly delisted; no price data found  (period=2y) (Yahoo error = \"No data found, symbol may be delisted\")\n",
            "ERROR:yfinance:$SUVENPHAR.NS: possibly delisted; no price data found  (period=2y) (Yahoo error = \"No data found, symbol may be delisted\")\n",
            "ERROR:yfinance:$SWANENERGY.NS: possibly delisted; no price data found  (period=2y) (Yahoo error = \"No data found, symbol may be delisted\")\n",
            "ERROR:yfinance:$TATAMOTORS.NS: possibly delisted; no price data found  (period=2y) (Yahoo error = \"No data found, symbol may be delisted\")\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Telegram BOT_TOKEN या MY_CHAT_ID वातावरण चर में सेट नहीं हैं। Telegram संदेश नहीं भेजा गया।\n",
            "\n",
            "--- Final Results (Printed to Console) ---\n",
            "*Nifty 500 Weekly Breakout Scan Results*\n",
            "\n",
            "\n",
            "*--- ब्रेकआउट सिग्नल वाले स्टॉक्स ---*\n",
            "\n",
            "- BOSCHLTD.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ABOSCHLTD)\n",
            "  `Close: 41475.0, Rolling High: 41385.0`\n",
            "- CGCL.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ACGCL)\n",
            "  `Close: 226.69, Rolling High: 225.99`\n",
            "- DELHIVERY.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ADELHIVERY)\n",
            "  `Close: 508.45, Rolling High: 491.7`\n",
            "- NYKAA.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ANYKAA)\n",
            "  `Close: 313.7, Rolling High: 309.75`\n",
            "- LTF.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ALTF)\n",
            "  `Close: 315.0, Rolling High: 307.8`\n",
            "- LAURUSLABS.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ALAURUSLABS)\n",
            "  `Close: 1525.5, Rolling High: 1492.6`\n",
            "- MARICO.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3AMARICO)\n",
            "  `Close: 856.25, Rolling High: 848.8`\n",
            "- OBEROIRLTY.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3AOBEROIRLTY)\n",
            "  `Close: 1856.8, Rolling High: 1784.0`\n",
            "- PAGEIND.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3APAGEIND)\n",
            "  `Close: 42900.0, Rolling High: 41905.0`\n",
            "- PHOENIXLTD.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3APHOENIXLTD)\n",
            "  `Close: 2009.0, Rolling High: 1944.5`\n",
            "- SUNDRMFAST.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ASUNDRMFAST)\n",
            "  `Close: 945.0, Rolling High: 944.36`\n",
            "- TRIVENI.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3ATRIVENI)\n",
            "  `Close: 465.5, Rolling High: 435.0`\n",
            "- VARROC.NS: [TradingView](https://in.tradingview.com/chart/?symbol=NSE%3AVARROC)\n",
            "  `Close: 660.0, Rolling High: 633.85`\n",
            "\n",
            "*--- डेटा नहीं मिल पाया वाले स्टॉक्स (छोड़ा गया) ---*\n",
            "\n",
            "निम्नलिखित स्टॉक्स के लिए ऐतिहासिक डेटा उपलब्ध नहीं था या उसे प्राप्त करने में त्रुटि हुई:\n",
            "\n",
            "- GMRINFRASTRUCT.NS\n",
            "- GSPL.NS\n",
            "- ISEC.NS\n",
            "- LTIM.NS\n",
            "- PEL.NS\n",
            "- SUVENPHAR.NS\n",
            "- SWANENERGY.NS\n",
            "- TATAMOTORS.NS\n"
          ]
        }
      ],
      "source": [
        "import yfinance as yf\n",
        "from datetime import datetime\n",
        "import pandas as pd\n",
        "import requests # For Telegram API\n",
        "import os # For environment variables\n",
        "\n",
        "def get_daily_data(symbol, period=\"2y\"):\n",
        "    \"\"\"yfinance से raw daily OHLCV list of dicts nikalo (no pandas)\"\"\"\n",
        "    ticker = yf.Ticker(symbol)\n",
        "    try:\n",
        "        hist = ticker.history(period=period)\n",
        "        if hist.empty:\n",
        "            return []\n",
        "    except Exception as e:\n",
        "        return []\n",
        "\n",
        "    hist = hist.reset_index()\n",
        "    data = []\n",
        "    for _, row in hist.iterrows():\n",
        "        if 'Date' not in row:\n",
        "            continue\n",
        "        data.append({\n",
        "            'date': row['Date'].to_pydatetime(),\n",
        "            'open': float(row['Open']),\n",
        "            'high': float(row['High']),\n",
        "            'low': float(row['Low']),\n",
        "            'close': float(row['Close']),\n",
        "            'volume': float(row['Volume'])\n",
        "        })\n",
        "    return data\n",
        "\n",
        "def to_weekly(daily_data):\n",
        "    \"\"\"Daily candles को ISO week के हिसाब से weekly OHLCV में aggregate करो\"\"\"\n",
        "    weeks = {}\n",
        "    for row in daily_data:\n",
        "        year, week, _ = row['date'].isocalendar()\n",
        "        key = (year, week)\n",
        "        if key not in weeks:\n",
        "            weeks[key] = {\n",
        "                'date': row['date'], 'open': row['open'],\n",
        "                'high': row['high'], 'low': row['low'],\n",
        "                'close': row['close'], 'volume': row['volume']\n",
        "            }\n",
        "        else:\n",
        "            w = weeks[key]\n",
        "            w['high'] = max(w['high'], row['high'])\n",
        "            w['low'] = min(w['low'], row['low'])\n",
        "            w['close'] = row['close']          # last close of week\n",
        "            w['volume'] += row['volume']\n",
        "            w['date'] = row['date']            # update to last date in week\n",
        "\n",
        "    # sorted list return करो (chronological)\n",
        "    return [weeks[k] for k in sorted(weeks.keys())]\n",
        "\n",
        "def weekly_breakout_scan(symbol, lookback_weeks=20, vol_multiplier=1.5):\n",
        "    daily = get_daily_data(symbol)\n",
        "    if not daily:\n",
        "        return None\n",
        "\n",
        "    weekly = to_weekly(daily)\n",
        "\n",
        "    if len(weekly) < lookback_weeks + 11:\n",
        "        return None  # पर्याप्त डेटा नहीं\n",
        "\n",
        "    latest = weekly[-1]\n",
        "\n",
        "    # rolling high of previous N weeks (excluding current week)\n",
        "    prev_weeks = weekly[-(lookback_weeks+1):-1]\n",
        "    if not prev_weeks:\n",
        "        return None\n",
        "    rolling_high = max(w['high'] for w in prev_weeks)\n",
        "\n",
        "    # avg volume of last 10 weeks (excluding current)\n",
        "    vol_window = weekly[-11:-1]\n",
        "    if not vol_window:\n",
        "        return None\n",
        "    avg_vol = sum(w['volume'] for w in vol_window) / len(vol_window)\n",
        "\n",
        "    breakout = latest['close'] > rolling_high\n",
        "    vol_confirm = latest['volume'] > vol_multiplier * avg_vol\n",
        "    strong_close = latest['close'] > (latest['low'] + 0.66 * (latest['high'] - latest['low']))\n",
        "\n",
        "    return {\n",
        "        'symbol': symbol,\n",
        "        'close': round(latest['close'], 2),\n",
        "        'rolling_high': round(rolling_high, 2),\n",
        "        'breakout': breakout,\n",
        "        'vol_confirm': vol_confirm,\n",
        "        'strong_close': strong_close,\n",
        "        'signal': breakout and vol_confirm and strong_close\n",
        "    }\n",
        "\n",
        "def send_telegram_message(message, bot_token, chat_id):\n",
        "    url = f\"https://api.telegram.org/bot{bot_token}/sendMessage\"\n",
        "    payload = {\n",
        "        'chat_id': chat_id,\n",
        "        'text': message,\n",
        "        'parse_mode': 'Markdown'\n",
        "    }\n",
        "    try:\n",
        "        response = requests.post(url, json=payload)\n",
        "        response.raise_for_status() # Raise an exception for HTTP errors\n",
        "        print(\"Telegram message sent successfully.\")\n",
        "    except requests.exceptions.RequestException as e:\n",
        "        print(f\"Error sending Telegram message: {e}\")\n",
        "\n",
        "# --- Nifty 500 के लिए परिवर्तन शुरू ---\n",
        "print(\"Nifty 500 सिंबल लाए जा रहे हैं...\")\n",
        "try:\n",
        "    url = 'https://en.wikipedia.org/wiki/NIFTY_500'\n",
        "    tables = pd.read_html(url, storage_options={'User-Agent': \"Mozilla/5.0\"}, match='Symbol', header=0)\n",
        "\n",
        "    nifty500_df = None\n",
        "    for table in tables:\n",
        "        if 'Symbol' in table.columns and 'Company Name' in table.columns:\n",
        "            nifty500_df = table\n",
        "            break\n",
        "\n",
        "    if nifty500_df is not None:\n",
        "        symbols_list = nifty500_df['Symbol'].dropna().astype(str).tolist()\n",
        "        symbols = [symbol + \".NS\" for symbol in symbols_list if not symbol.startswith('^')]\n",
        "        print(f\"सफलतापूर्वक {len(symbols)} Nifty 500 सिंबल लाए गए।\")\n",
        "    else:\n",
        "        print(\"Wikipedia पर NIFTY 500 तालिका नहीं मिली। डिफ़ॉल्ट सिंबल का उपयोग किया जा रहा है।\")\n",
        "        symbols = [\"RELIANCE.NS\", \"TCS.NS\", \"INFY.NS\"] # मूल पर वापस आ रहा है\n",
        "except Exception as e:\n",
        "    print(f\"Wikipedia से Nifty 500 सिंबल लाने में त्रुटि: {e}। डिफ़ॉल्ट सिंबल का उपयोग किया जा रहा है।\")\n",
        "    symbols = [\"RELIANCE.NS\", \"TCS.NS\", \"INFY.NS\"] # मूल पर वापस आ रहा है\n",
        "# --- Nifty 500 के लिए परिवर्तन समाप्त ---\n",
        "\n",
        "\n",
        "print(\"Nifty 500 स्टॉक्स के लिए साप्ताहिक ब्रेकआउट स्कैन चलाया जा रहा है...\")\n",
        "\n",
        "breakout_signals = [] # सिग्नल True वाले स्टॉक्स को स्टोर करने के लिए सूची\n",
        "data_fetch_errors = [] # yfinance data fetching errors को स्टोर करने के लिए सूची\n",
        "\n",
        "for sym in symbols:\n",
        "    result = weekly_breakout_scan(sym)\n",
        "    if result is None:\n",
        "        data_fetch_errors.append(sym)\n",
        "        continue # Skip to next symbol\n",
        "\n",
        "    if result['signal']:\n",
        "        # print(f\"BREAKOUT SIGNAL: {result}\") # अगर आप सभी रिजल्ट देखना चाहते हैं तो इसे अनकमेंट करें\n",
        "        breakout_signals.append(result)\n",
        "\n",
        "# Construct the message for Telegram\n",
        "telegram_message_parts = [\"*Nifty 500 Weekly Breakout Scan Results*\\n\"]\n",
        "\n",
        "if breakout_signals:\n",
        "    telegram_message_parts.append(\"\\n*--- ब्रेकआउट सिग्नल वाले स्टॉक्स ---*\\n\")\n",
        "    for signal_data in breakout_signals:\n",
        "        b_sym = signal_data['symbol']\n",
        "        tv_symbol = b_sym.replace('.NS', '')\n",
        "        tradingview_link = f\"https://in.tradingview.com/chart/?symbol=NSE%3A{tv_symbol}\"\n",
        "        telegram_message_parts.append(f\"- {b_sym}: [TradingView]({tradingview_link})\\n  `Close: {signal_data['close']}, Rolling High: {signal_data['rolling_high']}`\")\n",
        "else:\n",
        "    telegram_message_parts.append(\"इस स्कैन में कोई ब्रेकआउट सिग्नल नहीं मिला।\")\n",
        "\n",
        "if data_fetch_errors:\n",
        "    telegram_message_parts.append(\"\\n*--- डेटा नहीं मिल पाया वाले स्टॉक्स (छोड़ा गया) ---*\\n\")\n",
        "    telegram_message_parts.append(\"निम्नलिखित स्टॉक्स के लिए ऐतिहासिक डेटा उपलब्ध नहीं था या उसे प्राप्त करने में त्रुटि हुई:\\n\")\n",
        "    for err_sym in data_fetch_errors:\n",
        "        telegram_message_parts.append(f\"- {err_sym}\")\n",
        "\n",
        "final_telegram_message = \"\\n\".join(telegram_message_parts)\n",
        "\n",
        "# Get Telegram credentials from environment variables\n",
        "bot_token = os.getenv('BOT_TOKEN')\n",
        "chat_id = os.getenv('MY_CHAT_ID')\n",
        "\n",
        "if bot_token and chat_id:\n",
        "    send_telegram_message(final_telegram_message, bot_token, chat_id)\n",
        "else:\n",
        "    print(\"Telegram BOT_TOKEN या MY_CHAT_ID वातावरण चर में सेट नहीं हैं। Telegram संदेश नहीं भेजा गया।\")\n",
        "    print(\"\\n--- Final Results (Printed to Console) ---\")\n",
        "    print(final_telegram_message) # Print to console if Telegram not configured"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "c2da0bb7"
      },
      "source": [
        "## GitHub Actions Workflow (`.github/workflows/weekly_breakout_scan.yml`)\n",
        "\n",
        "This workflow will run your Python script on a weekly schedule to identify breakout stocks and send Telegram notifications."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "847401c1"
      },
      "source": [
        "```yaml\n",
        "name: Weekly Stock Breakout Scan\n",
        "\n",
        "on:\n",
        "  schedule:\n",
        "    # Runs daily at 3:01 PM UTC (15:01 UTC)\n",
        "    - cron: '1 15 * * *'\n",
        "  workflow_dispatch: # Allows manual triggering of the workflow\n",
        "\n",
        "jobs:\n",
        "  run_scan:\n",
        "    runs-on: ubuntu-latest\n",
        "\n",
        "    steps:\n",
        "    - name: Checkout repository\n",
        "      uses: actions/checkout@v3\n",
        "\n",
        "    - name: Set up Python\n",
        "      uses: actions/setup-python@v4\n",
        "      with:\n",
        "        python-version: '3.x'\n",
        "\n",
        "    - name: Install dependencies\n",
        "      run: |\n",
        "        python -m pip install --upgrade pip\n",
        "        pip install yfinance pandas requests\n",
        "\n",
        "    - name: Run weekly breakout scan script\n",
        "      env:\n",
        "        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}\n",
        "        MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}\n",
        "      run: |\n",
        "        python breakout_in_weekly_chart.py\n",
        "```"
      ]
    }
  ]
}