name: CAR_BOT_STOCK_ALERT

on:
  schedule:
    # भारतीय समयानुसार (IST) रोज सुबह 6:00 बजे ऑटोमैटिक चलेगा
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install gspread oauth2client requests

      - name: Run Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
        run: python car_buy.py
        
