name: Stock News Bot

on:
  workflow_dispatch:

 # schedule:
    # 8:00 AM IST
 #   - cron: "30 2 * * *"

    # 8:00 PM IST
  # - cron: "30 14 * * *"

jobs:

  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests
          pip install beautifulsoup4
          pip install python-telegram-bot
          pip install feedparser

      - name: Run Stock News Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}

        run: |
          python stock_news.py